### ISSUE TITLE
Support actualsub

### ISSUE THREAD

**Issue by omsmith** [Brightspace/node-auth-token#10]

**Comment by j3parker** [comment]
One difference from LP that I put into D2L.Security.OAuth2 is that on ID2LPrincipal "ActualUserId" always returns something (if a user,) it'll just match the UserId part if no impersonation is happening. From what I've seen this will reduce branching in special areas that want to ignore impersonation (but a `if( UserId != ActualUserId)` does come up if you want to do something different for impersonation... maybe an `ID2LPrincipal.IsImpersonating` would be good in the future for readability if we find this happens a lot.)
